### ISSUE TITLE
authentication fails

### ISSUE THREAD

**Issue by ericsfraga** [dickmao/nntwitter#1]
I've added nntwitter to my secondary select methods but as soon as I start gnus, it fails with
`nntwitter-api-set-oauth-tokens: ‘nntwitter-api-set-oauth-tokens’: authentication failure`
I did originally have eww as my default browser. I did change this to default browser so that Firefox pops up. I do get the twitter authentication page which gives me a PIN but there is nowhere to type that pin in within Emacs.

**Comment by dickmao** [comment]
> nowhere to type that pin in within Emacs.

Note after `M-x nntwitter-api-route-auth`, a `*Warnings*` window says "Please check your browser" and the minibuffer prompts "PIN".

![nntwitter-pin](https://user-images.githubusercontent.com/7578770/103461553-30864c80-4ced-11eb-8ea0-d26d245dbc74.gif)

If you are not seeing either of these, and if your waning interest can sustain it, you'd need to add print statements [here](https://github.com/dickmao/nntwitter/blob/94916ad8c3e3bf697855c58257f92cd697c9521a/lisp/nntwitter-api.el#L101) to see why after firefox pops up, the above behaviors do not exhibit.

**Comment by ericsfraga** [comment]
I saw neither the warning window nor the minibuffer prompt for the PIN. And I checked my *Messages* buffer just in case I missed something but there was nothing there beyond the error message shown above.
I am curious: why is my interest waning? 
In any case, I'm surprised you have closed this issue. But, okay.

**Comment by dickmao** [comment]
I cannot tell from your response whether you "saw neither the warning window nor the minibuffer prompt" when recollecting your initial attempt at nntwitter, or if you manually followed my prescription of `M-x nntwitter-api-route-route-auth`.  If the latter, then I remain curious as to what the aforementioned print statements might reveal, but my experience is that users (myself included) rarely attempt this kind of debugging.  Thus, my remark about "waning interest."

**Comment by ericsfraga** [comment]
Ah, okay. I did not see any such windows and I did not try the command directly. I had simply started gnus. Trying the command directly gets me no further unfortunately. I have put a print statement where indicated and it appears (i.e. is executed) but no PIN prompt appears.

**Comment by dickmao** [comment]
Then it must be erroring out.  I would set `M-x toggle-debug-on-error`, then retry `M-x nntwitter-api-route-auth`.

**Comment by ericsfraga** [comment]
Yes:
```
Debugger entered--Lisp error: (wrong-type-argument listp "")
warning-suppress-p("" ((emacs) (undo discard-info)))
display-warning("" "Please check your browser and follow the instructi..." :warning)

```

**Comment by dickmao** [comment]
Sorry about that.  Commit 01a6fa1.  Thanks for reporting the bug.

**Comment by ericsfraga** [comment]
Thank you! I will try this later (busy with online teaching at the moment.... the joys of the pandemic).
